server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RequestTrackingDB
    username: ${PGUSER}
    password: ${PGPASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${SECRET}
  expiration: 86400000